//
//  CheckListsModels.swift
//  SmartContrakt
//
//  Created by Артем Валиев on 03/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CheckLists
{
  // MARK: Use cases
  
    
    enum CreateCheckList {
        struct Request {
            let model: TemplateModel
            let date: Date
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }

    enum RemoveCheckList {
        struct Request {
            let id: String
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        let checkLists: [CheckListModel]
    }
    struct ViewModel
    {
        let checkLists: [CheckListModel]
    }
  }
}
