//
//  RequirementsInteractor.swift
//  SmartContrakt
//
//  Created by Артем Валиев on 04/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RequirementsBusinessLogic
{
  func doSomething(request: Requirements.Something.Request)
}

protocol RequirementsDataStore
{
  //var name: String { get set }
}

class RequirementsInteractor: RequirementsBusinessLogic, RequirementsDataStore
{
  var presenter: RequirementsPresentationLogic?
  var worker: RequirementsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Requirements.Something.Request)
  {
    worker = RequirementsWorker()
    worker?.doSomeWork()
    
    let response = Requirements.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
