//
//  RequirementsInteractor.swift
//  SmartContrakt
//
//  Created by Артем Валиев on 04/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RequirementsBusinessLogic
{
  func loadRequirementsIfEmpty(request: Requirements.Something.Request)
}

protocol RequirementsDataStore
{
  //var name: String { get set }
}

class RequirementsInteractor: RequirementsBusinessLogic, RequirementsDataStore
{
  var presenter: RequirementsPresentationLogic?
  
  func loadRequirementsIfEmpty(request: Requirements.Something.Request)
  {

    api.getRequirementsForCheckList(action: API.Action.getRequirementsForMy(checkListId: request.checkListId)) { (requirements) in
        
    }
    
    let response = Requirements.Something.Response()
    presenter?.presentRequirements(response: response)
  }
}
