//
//  RequirementsPresenter.swift
//  SmartContrakt
//
//  Created by Артем Валиев on 04/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RequirementsPresentationLogic
{
  func presentRequirements(response: Requirements.Something.Response)
}

class RequirementsPresenter: RequirementsPresentationLogic
{
  weak var viewController: RequirementsDisplayLogic?
  
  // MARK: Do something
  
  func presentRequirements(response: Requirements.Something.Response)
  {
    let viewModel = Requirements.Something.ViewModel(requirements: response.requirements)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
