//
//  CheckListsPresenter.swift
//  SmartContrakt
//
//  Created by Артем Валиев on 03/12/2018.
//  Copyright (c) 2018 Артем Валиев. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CheckListsPresentationLogic
{
  func displayCheckLists(response: CheckLists.Something.Response)
}

class CheckListsPresenter: CheckListsPresentationLogic
{
  weak var viewController: CheckListsDisplayLogic?
  
  // MARK: Do something
  
  func displayCheckLists(response: CheckLists.Something.Response)
  {
    let viewModel = CheckLists.Something.ViewModel(checkLists: response.checkLists)
    viewController?.displayCheckLists(viewModel: viewModel)
  }
}
